CREATE DATABASE IF NOT EXISTS mascotas_db;
USE mascotas_db;


-- TABLA USUARIOS

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- TABLA MASCOTAS

CREATE TABLE IF NOT EXISTS mascotas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    especie VARCHAR(50) NOT NULL,
    raza VARCHAR(80) NOT NULL,
    edad INT NOT NULL,
    ubicacion VARCHAR(120) NOT NULL,
    estado_adopcion VARCHAR(30) NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


-- ÍNDICES

CREATE INDEX idx_especie ON mascotas(especie);
CREATE INDEX idx_ubicacion ON mascotas(ubicacion);
CREATE INDEX idx_estado ON mascotas(estado_adopcion);